services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "11"
      GPU: "Y"
      USER_PORTS: "3389,9876"
      SKETCHUP_INSTALLER: ${SKETCHUP_INSTALLER:-./installers/SketchUp2025.exe}
    devices:
      - /dev/dri
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
      - 6123:6123 # VS Code debug port
      - 9876:9876 # TCP port for sketchup-link live sync
    volumes:
      - ./vm-storage:/storage
      - ./shared:/shared
      - ./oem:/oem
    restart: always
    stop_grace_period: 2m
  blender:
    build:
      context: ..
      dockerfile: integration/Dockerfile.blender
    container_name: blender
    volumes:
      - ./screenshots:/screenshots
    depends_on:
      - windows
    restart: "no"
